all:
  children:
    aws:
      hosts:
        ec2:
          ansible_host: EC2_PUBLIC_IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /path/to/private_key
          ansible_python_interpreter: /usr/bin/python3